server:
  port: 8081
  servlet:
    context-path: /
  compression:
    enabled: true
  address: 0.0.0.0
spring:
  profiles:
#    active: prometheus
    active: all
  thymeleaf:
    cache: false
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      maximum-pool-size: 5
      connection-test-query: "SELECT 1"
      pool-name: cemsPool
      connection-timeout: 60000
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework: DEBUG
    com.apress.cems.boot: DEBUG

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans,mapping,configprops
info:
  app:
    name: Spring Actuator Application
    description: This is a very simple Spring Boot Application
    version: 1.0-SNAPSHOT