server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: sample
    password: sample
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect